#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada 
print('---------CALCULADORA DE TABUADA---------')
n = int(input('Digite um número INTEIRO qualquer: '))
print(f'---TABUADA DO NUMERO {n}---')
print(f'{n} X 1 = {1 *n}')
print(f'{n} X 2 = {2 *n}')
print(f'{n} X 3 = {3 *n}')
print(f'{n} X 4 = {4 *n}')
print(f'{n} X 5 = {5 *n}')
print(f'{n} X 6 = {6 *n}')
print(f'{n} X 7 = {7 *n}')
print(f'{n} X 8 = {8 *n}')
print(f'{n} X 9 = {9 *n}')
print(f'{n} X 10 = {10 *n}')